// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensibilityLogs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "7eec6573-16c8-4fab-9de3-0b9520f4b08d";
        public static Guid Package = new Guid(PackageString);

        public const string PackageCommandSetString = "ce6c0c30-b2b2-432e-96fa-0acd36855968";
        public static Guid PackageCommandSet = new Guid(PackageCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageToolbar = 0xA001;
        public const int LogGroup = 0x0700;
    }
}