// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensibilityLogs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "0298784e-e549-4e67-b3f3-af01a28a9f88";
        public static Guid Package = new Guid(PackageString);

        public const string PackageCommandSetString = "2275760e-e992-461e-ae66-2e42f176d277";
        public static Guid PackageCommandSet = new Guid(PackageCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageToolbar = 0x0000;
        public const int PackageMenu = 0x0005;
        public const int PackageGroup = 0x0010;
        public const int PackageMenuGroup = 0x0015;
        public const int LogGroup = 0x0020;
        public const int ToolGroup = 0x0025;
        public const int ActivityLogCommand = 0x0100;
        public const int DiagnosticLogCommand = 0x0105;
        public const int MefErrorLogCommand = 0x0110;
        public const int ServiceHubLogCommand = 0x0115;
        public const int VsixInstallerLogCommand = 0x0120;
        public const int EnvironmentVariablesCommand = 0x0200;
        public const int PathVariablesCommand = 0x0205;
        public const int VisualStudioFolderCommand = 0x0210;
        public const int PackageOptionsCommand = 0x0500;
    }
}